export const RESET_STORE = 'RESET_STORE';

export const SHOW_CREATE_EVENT_SPINNER = 'SHOW_CREATE_EVENT_SPINNER';
export const LOAD_CREATE_EVENT_SUCCESS = 'LOAD_CREATE_EVENT_SUCCESS';
export const LOAD_CREATE_EVENT_FAILED = 'LOAD_CREATE_EVENT_FAILED';
export const PURGE_CREATE_EVENT = 'PURGE_CREATE_EVENT';


export const SHOW_UPDATE_EVENT_SPINNER = 'SHOW_UPDATE_EVENT_SPINNER';
export const LOAD_UPDATE_EVENT_SUCCESS = 'LOAD_UPDATE_EVENT_SUCCESS';
export const LOAD_UPDATE_EVENT_FAILED = 'LOAD_UPDATE_EVENT_FAILED';
export const PURGE_UPDATE_EVENT = 'PURGE_UPDATE_EVENT';

export const SHOW_GET_EVENTS_SPINNER = 'SHOW_GET_EVENTS_SPINNER';
export const LOAD_GET_EVENTS_SUCCESS = 'LOAD_GET_EVENTS_SUCCESS';
export const LOAD_GET_EVENTS_FAILED = 'LOAD_GET_EVENTS_FAILED';
export const PURGE_GET_EVENTS = 'PURGE_GET_EVENTS';

export const SHOW_CONFIGURATE_WEEKLY_SPINNER = 'SHOW_CONFIGURATE_WEEKLY_SPINNER';
export const LOAD_CONFIGURATE_WEEKLY_SUCCESS = 'LOAD_CONFIGURATE_WEEKLY_SUCCESS';
export const LOAD_CONFIGURATE_WEEKLY_FAILED = 'LOAD_CONFIGURATE_WEEKLY_FAILED';
export const PURGE_CONFIGURATE_WEEKLY = 'PURGE_CONFIGURATE_WEEKLY';

export const SHOW_UPDATE_WEEKLY_SPINNER = 'SHOW_UPDATE_WEEKLY_SPINNER';
export const LOAD_UPDATE_WEEKLY_SUCCESS = 'LOAD_UPDATE_WEEKLY_SUCCESS';
export const LOAD_UPDATE_WEEKLY_FAILED = 'LOAD_UPDATE_WEEKLY_FAILED';
export const PURGE_UPDATE_WEEKLY = 'PURGE_UPDATE_WEEKLY';

export const SHOW_GET_WEEKLY_HOURS_SPINNER = 'SHOW_GET_WEEKLY_HOURS_SPINNER';
export const LOAD_GET_WEEKLY_SUCCESS = 'LOAD_GET_WEEKLY_SUCCESS';
export const LOAD_GET_WEEKLY_FAILED = 'LOAD_GET_WEEKLY_FAILED';
export const PURGE_GET_WEEKLY = 'PURGE_GET_WEEKLY';

export const SHOW_GET_AVAILABILITY_SPINNER = 'SHOW_GET_AVAILABILITY_SPINNER';
export const LOAD_GET_AVAILABILITY_SUCCESS = 'LOAD_GET_AVAILABILITY_SUCCESS';
export const LOAD_GET_AVAILABILITY_FAILED = 'LOAD_GET_AVAILABILITY_FAILED';
export const PURGE_GET_AVAILABILITY = 'PURGE_GET_AVAILABILITY';






